### ISSUE TITLE
Joints not being properly set in setup

### ISSUE THREAD

**Issue by samkhal** [samkhal/biped#19]
Joint index read from EEPROM is not used, so teensy cannot properly identify it's joints.

https://github.com/samkhal/biped/blob/4e3fae089adf8a3813d6b54db1dc61aef925aadc/onboard/main.cpp#L227-L229

@gardamerinos

**Comment by samkhal** [comment]
Also, @gardamerinos in general, I'm lost as to how each teensy knows what joints belong to it.

**Comment by gardamerinos** [comment]
I was confused in the beginning too, but the get method assigns the value to the variable passed. This is why index is just declared. This index number in the ROM should be from 1 to 12. The reason it works like this is because otherwise the get method of EEPROM would not know what type the variable it is going to read is.

**Comment by samkhal** [comment]
I know how the get method works, but you're getting data from EEPROM, storing it in `index`, and then never using that variable. Did you mean to do something like `JointTable[index]` on the next line? As it's written only the first three rows of the JointTable are ever used.

**Comment by gardamerinos** [comment]
Yes you are totally right, I should use index to get the value of the JointTable. I missed that, next line should definitely have JointTable[index-1] but the rest should be joints[i].

**Comment by samkhal** [comment]
Fixed in https://github.com/samkhal/biped/pull/21
